# lima1.yml
---

samba_workgroup: green.local
samba_server_string: 'Welcome to the green samba server'
samba_security: user
samba_load_homes: true
samba_log: /var/log/samba.log
samba_log_size: 60000
samba_create_varwww_symlinks: true


rhbase_user_groups:
  - itadministratie
  - verkoop
  - administratie
  - ontwikkeling
  - directie


rhbase_users:
  - name: lander
    comment: 'Lander Van den Bulcke'
    groups:
      - itadministratie


  - name: torvalds
    comment: 'Linus Torvalds'
    groups:
      - verkoop

  - name: rms
    comment: 'Richard Stallman'
    groups:
     - administratie

  - name: knuth
    comment: 'Donald Knuth'
    groups:
     - ontwikkeling

  - name: dmr
    comment: 'Dennis Ritchie'
    groups:
     - directie


samba_users:
  - name: lander
    password: "password"
    group: itadministratie

  - name: torvalds
    password: "password"
    group: verkoop

  - name: rms
    password: "password"
    group: administratie

  - name: knuth
    password: "password"
    group: ontwikkeling

  - name: dmr
    password: "password"
    group: directie

rhbase_firewall_allow_services:
   - samba
   # - samba-client


samba_shares:
   - name: itadministratie
     group: itadministratie
     write_list: +itadministratie
     

   - name: verkoop
     group: verkoop
     write_list: +verkoop


   - name: administratie
     group: administratie
     write_list: +administratie


   - name: ontwikkeling
     group: ontwikkeling
     write_list: +ontwikkeling


   - name: directie
     group: directie
     write_list: +directie



#samba_security: domain
#samba_passdb_backend: ldapsam:ldap://alfa1.green.local
# samba_rootdn: "cn=admin"
# samba_suffix: "dc=green,dc=local"
# samba_user_suffix: "ou=People"
# samba_machine_suffix: "ou=Computers"
# samba_group_suffix: "ou=Groups"

# samba_local_master: false

#samba_ssl: "off"
#samba_sync: "yes"

#tasks:
#  - script: ../scripts/Lima/Lima.sh

#samba_hosts_allow: 172.16.128.132

beats_config_file: files/servers.yml
