---
#wordpress

rhbase_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

rhbase_firewall_allow_ports:
  - 389/tcp

httpd_DocumentRoot: '/usr/share/wordpress'

php_packages_extra:
  - php-ldap

#November integratie
wordpress_database_host: 172.16.128.7
wordpress_database: mike1DB
wordpress_user: mike1
wordpress_password: mike1

wordpress_plugins:
  - name: ldap-login-for-intranet-sites
  - name: simple-ldap-login
  - name: authLdap
  - name: wpDirAuth
  - name: active-directory-authentication-integration

wordpress_themes:
  - name: xcel
    version: 1.0.9

beats_config_file: files/servers.yml
