# roles/pxeserver/vars/main.yml
---

pxeserver_packages:
  - rsync
  - shim
  - syslinux
  - httpd

pxeserver_services:
  - httpd
  - tftp

pxeserver_files:
  - /usr/share/syslinux/pxelinux.0
  - /usr/share/syslinux/menu.c32
  - /boot/efi/EFI/BOOT/BOOTX64.EFI
