---
# Configure beats package.

- name: "Configure {{ beats_package_name }}."
  copy:
    src: "{{ beats_config_file }}"
    dest: "/etc//{{ beats_package_name }}/{{ beats_package_name }}.yml"
  notify: restart beat