---
galaxy_info:
  author: Bert Van Vreckem
  description: This role installs and configures Samba as a file server.
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 25
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - jessie
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - system
    - networking
dependencies: []
