# roles/samba/vars/os_Debian.yml
---

samba_packages:
  - samba-common
  - samba
  - samba-client

samba_selinux_packages: []
samba_selinux_booleans: []

samba_configuration: /etc/samba/smb.conf

# The name of the Samba service in older releases (Ubuntu 14.04,
# Debian <8) is "samba".
samba_services:
  - smbd
  - nmbd

samba_www_documentroot: /var/www
